kind: pipeline
name: default

steps: 
   
- name: publish_docker
  image: plugins/docker
  settings:
    username: prakashshettigar23
    password: *#Pra9902694945
    repo: prakashshettigar23/networkapp
    registry: index.docker.io
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    tags:
      - latest
  when:
    event:
    - push
    - tag