kind: pipeline
name: default

steps: 
   
- name: publish_docker
  image: plugins/docker
  settings:
    tag: 
        - latest
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: prakashshettigar23/networkapp
    registry: index.docker.io
    dockerfile : /drone/src/DockerFile
    context: /drone/src
  when:
    event:
    - push
    - tag