kind: pipeline
name: default

steps: 
   
- name: publish_docker
  image: plugins/docker
  settings:
    tag: 
        - latest
    repo: cloud.docker.com/repository/docker/prakashshettigar23/networkapp
    registry: index.docker.io
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    commands:
        - ls
        - pwd
  when:
    event:
    - push
    - tag