pipeline:
    "[DOCKER] build networkapp": #Docker build for networkapp
        image: plugins/docker
        repo: cloud.docker.com/repository/docker/prakashshettigar23/devopsautomation
        registry: cloud.docker.com
        secrets: [ docker_username, docker_password ]
        tags:
            - latest
            - networkapp-0.1-SNAPSHOT-${DRONE_BUILD_NUMBER}  
        dockerfile: ./ms/syncms/docker/Dockerfile
        context: ./ms/syncms
        when:
            event: [push]