kind: pipeline
name: default

steps: 
- name: frontend
  image: node
  commands:
    - ls
    - pwd
    - cd ..
    - ls
    - cd /drone/src/
    - ls
   
- name: publish_docker
  image: plugins/docker
  settings:
    tag: 
        - latest
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: cloud.docker.com/repository/docker/prakashshettigar23/networkapp
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    commands:
        - ls
        - pwd
  when:
    event:
    - push
    - tag