kind: pipeline
name: default

steps:    
- name: publish_docker
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker_password
    repo: cloud.docker.com/repository/docker/prakashshettigar23/networkapp
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag