kind: pipeline
name: default

steps: 
- name: publish_docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: prakashshettigar23/networkapp
    tags:
      - latest
  when:
    event:
    - push
    - tag