kind: pipeline
name: default

steps: 
- name: publish_docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: prakashshettigar23/networkapp
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    tags:
      - latest
      - manhunt-0.1-SNAPSHOT-${DRONE_BUILD_NUMBER}
  #when:
  #  event:
  #  - push
  #  - tag
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  host: https://sonarcloud.io
  when:
    event:
    - push
    - tag   
    
# https://sonarcloud.io/project/issues?id=prakashettigar_Python&resolved=false   
 #sonar-scanner.bat -D"sonar.projectKey=prakashettigar_Python" -D"sonar.organization=prakashettigar-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=54692686540985b96b0f6120e391752b217d32f4"