kind: pipeline
name: default

steps: 
- name: publish_docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: prakashshettigar23/networkapp
    dockerfile : /drone/src/DockerFile
    context: /drone/src
    tags:
      - latest
      - manhunt-0.1-SNAPSHOT-${DRONE_BUILD_NUMBER}
  when:
    event:
    - push
    - tag