kind: pipeline
name: default

steps: 
steps:
- name: frontend
  image: node
  commands:
    - ls
    - pwd
    - npm install
    - npm test
   
- name: publish_docker
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    repo: cloud.docker.com/repository/docker/prakashshettigar23/networkapp
    dockerfile: ./Phthon/Dockerfile
    context: ./Phthon/
  when:
    event:
    - push
    - tag