pipeline:
    "[DOCKER] build networkapp": #Docker build for networkapp
        image: plugins/docker
        repo: cloud.docker.com/repository/docker/prakashshettigar23/networkapp
        dockerfilePath: ./Dockerfile
        buildContext: .
        registry: index.docker.io
        secrets: [ docker_username, docker_password ]
        tags:
            - latest
            - networkapp-0.1-SNAPSHOT-${DRONE_BUILD_NUMBER}  
        when:
            event: [push]